# Start with a lightweight python 3 image
FROM python:3-alpine
# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Send python output in real-time without needing to be buffered
ENV PYTHONUNBUFFERED=1
# Don't write .pyc files when importing source modules
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /code
COPY pyproject.toml uv.lock ./

# Install the packages needed to install psycopg2-binary: https://stackoverflow.com/a/47871121
RUN \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    # Install all python dependencies
    uv sync --locked --no-cache && \
    apk --purge del .build-deps

COPY . .
WORKDIR /code/stockhelper
