# Generated by Django 3.1.5 on 2021-03-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='Stocks',
            new_name='Stock',
        ),
    ]
