# Generated by Django 3.1.5 on 2021-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
