# Generated by Django 3.1.5 on 2021-09-20 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='', max_length=10),
        ),
    ]
