# Generated by Django 3.1.5 on 2021-03-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_auto_20210318_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
