# Generated by Django 3.1.5 on 2021-09-25 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_auto_20210919_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
