# Generated by Django 3.1.5 on 2021-09-25 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20210924_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='ticker',
            new_name='stock',
        ),
    ]
